// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/DemoLib.h"

namespace winrt::DemoLib::implementation {

template <typename D, typename... I>
struct WINRT_EBO Person_base : implements<D, DemoLib::IPerson, I...>
{
    using base_type = Person_base;
    using class_type = DemoLib::Person;
    using implements_type = typename Person_base::implements_type;
    using implements_type::implements_type;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"DemoLib.Person";
    }
};

}

namespace winrt::DemoLib::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO PersonT : implements<D, Windows::Foundation::IActivationFactory, DemoLib::IPersonFactory, I...>
{
    hstring GetRuntimeClassName() const
    {
        return L"DemoLib.Person";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }

    DemoLib::Person CreateInstance(hstring const& name)
    {
        return make<T>(name);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_PERSON_XAML_G_H) || __has_include("Person.xaml.g.h")

#include "Person.xaml.g.h"

#else

namespace winrt::DemoLib::implementation
{
    template <typename D, typename... I>
    using PersonT = Person_base<D, I...>;
}

#endif
