// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/BindingViewModels.h"

namespace winrt::BindingViewModels::implementation {

template <typename D, typename... I>
struct WINRT_EBO MainViewModel_base : implements<D, BindingViewModels::IMainViewModel, Windows::UI::Xaml::Data::INotifyPropertyChanged, composing, I...>,
    impl::require<D, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>,
    impl::base<D, Windows::UI::Xaml::DependencyObject>
{
    using base_type = MainViewModel_base;
    using class_type = BindingViewModels::MainViewModel;
    using implements_type = typename MainViewModel_base::implements_type;
    using implements_type::implements_type;
    using composable_base = Windows::UI::Xaml::DependencyObject;
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"BindingViewModels.MainViewModel";
    }
    MainViewModel_base()
    {
        get_activation_factory<Windows::UI::Xaml::DependencyObject, Windows::UI::Xaml::IDependencyObjectFactory>().CreateInstance(*this, this->m_inner);
    }
};

}

namespace winrt::BindingViewModels::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO MainViewModelT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    hstring GetRuntimeClassName() const
    {
        return L"BindingViewModels.MainViewModel";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_MAINVIEWMODEL_XAML_G_H) || __has_include("MainViewModel.xaml.g.h")

#include "MainViewModel.xaml.g.h"

#else

namespace winrt::BindingViewModels::implementation
{
    template <typename D, typename... I>
    using MainViewModelT = MainViewModel_base<D, I...>;
}

#endif
