// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/ViewModelLib.0.h"

WINRT_EXPORT namespace winrt::ViewModelLib {

struct WINRT_EBO INotificationBase :
    Windows::Foundation::IInspectable,
    impl::consume_t<INotificationBase>
{
    INotificationBase(std::nullptr_t = nullptr) noexcept {}
};

}
