// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/DemoLib.0.h"

WINRT_EXPORT namespace winrt::DemoLib {

struct WINRT_EBO IPerson :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPerson>
{
    IPerson(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPersonFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPersonFactory>
{
    IPersonFactory(std::nullptr_t = nullptr) noexcept {}
};

}
