// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/DemoLib.1.h"

WINRT_EXPORT namespace winrt::DemoLib {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::DemoLib {

struct WINRT_EBO Person :
    DemoLib::IPerson
{
    Person(std::nullptr_t) noexcept {}
    Person();
    Person(param::hstring const& name);
};

}
