namespace ViewModelLib
{
    [default_interface]
    runtimeclass NotificationBase : Windows.UI.Xaml.DependencyObject, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        NotificationBase();

    }
}
